### ISSUE TITLE
Using `--setup_file` for dependency installation on workers     

### ISSUE THREAD

**Issue by daikeshi** [spotify/spotify-tensorflow#124]
It seems we can use `--setup_file` instead of `--requirements_file`, so we can install tfdv on workers. Currently, tfdv can't be installed via the requirements file and needs to be installed from a wheel package.

https://github.com/tensorflow/model-analysis/blob/master/examples/chicago_taxi/tfdv_analyze_and_validate_dataflow.sh#L64

https://github.com/tensorflow/model-analysis/blob/master/examples/chicago_taxi/setup.py

**Comment by daikeshi** [comment]
I made a simple setup.py to install tft and tfdv. It seems to work for me. We should probably consider using it to install the dependency on workers.

```
TF_VERSION = '1.11.0'

if __name__ == '__main__':
  setuptools.setup(
      name='tfx_chicago_taxi',
      version='0.11.0',
      packages=setuptools.find_packages(),
      install_requires=[
          'tensorflow==' + TF_VERSION,
          'tensorflow_data_validation',
          'tensorflow_transform',
          'tensorflow-metadata==0.9.0'
      ])
```

**Comment by daikeshi** [comment]
Discussed with @andrewsmartin, we'll wait to implement this after we remove pbr, so we can put all tfx requires in setup.py under `spotify-tensorflow` and pass it to workers

**Comment by brianmartin** [comment]
Neat. Nice find @daikeshi!

Would be interesting to test what's available in the environment when this setup.py is evaluated. If we have all the dependencies available then we could grab the TF version from whatever is installed.

**Comment by daikeshi** [comment]
Implemented in https://github.com/spotify/spotify-tensorflow/pull/164. `setup.py` only contains `spotify-tensorflow` as the required dependency.
