### ISSUE TITLE
tox: Remove reference to non-existent `tfdv` extras

### ISSUE THREAD

**Issue by brianmartin** [spotify/spotify-tensorflow#169]
https://github.com/spotify/spotify-tensorflow/blob/6765eaf27cf4569c4239441cb08e1416932f7791/tox.ini#L13

cc @daikeshi

**Comment by daikeshi** [comment]
Fixed in this branch https://github.com/spotify/spotify-tensorflow/tree/tf113 with a few other clean up. 
Will merge it and release into next version when tf-1.13 is out.

**Comment by brianmartin** [comment]
Awesome, thanks @daikeshi!

**Comment by brianmartin** [comment]
This is fixed on master.
