### ISSUE TITLE
Expose the job_name of TensorflowTask

### ISSUE THREAD

**Issue by martin-laurent** [spotify/spotify-tensorflow#172]
The value of the ML-Engine job name is unpredictable: https://github.com/spotify/spotify-tensorflow/blob/master/spotify_tensorflow/luigi/tensorflow_task.py#L139-L140
It would be great if this was generated in a protected method (that could be overridden by the user) or caught in a lazy parameter (that the user could access).
I think the first method is the best as it allows the user to use something different than a long uuid which is hard to read.

**Comment by brianmartin** [comment]
Done in attached PR.
