### ISSUE TITLE
Depend on tfx 0.13 when it's out

### ISSUE THREAD

**Issue by andrewsmartin** [spotify/spotify-tensorflow#187]
Instead of the individual libs.

**Comment by andrewsmartin** [comment]
https://github.com/tensorflow/tfx/releases

**Comment by brianmartin** [comment]
It's out! :)

**Comment by rclough** [comment]
looking to get this tested (and hopefully in) tomorrow

**Comment by rclough** [comment]
Addressed in e87abd0
