### ISSUE TITLE
TensorFlow compatibility problems 

### ISSUE THREAD

**Issue by TITAN-PyCompat** [spotify/spotify-tensorflow#194]
Dear developers,

I observed some TensorFlow API usage in your code that might lead to serious compatibility problems(like a crash).

In file `spotify-tensorflow/examples/example_tf_training_tfexample/main.py` you used `tf.concat` and used keyword `axis` to pass the value. However, the parameter `axis` appears in tf v1.0.0. The older parameter is called `concat_dim` in earlier version api. A crash would happen for an earlier version.

I have fixed this issue in #193 
Look forward to your reply! @jkp @mbruggmann @vzctl @dflemstr @protocol7 
Thanks!

**Comment by brianmartin** [comment]
This is spam. Definitely no one using TF 0.x.x.
