### ISSUE TITLE
spotify-tensorflow requires tfx==0.13.0

### ISSUE THREAD

**Issue by martin-laurent** [spotify/spotify-tensorflow#207]
spotify-tensorflow requires `tfx==0.13.0` but it's never actually used.
It's annoying when working with a project that actually uses it on a newer version.

**Comment by brianmartin** [comment]
Hey @martin-laurent, please see #206.

**Comment by martin-laurent** [comment]
@andrewsmartin There is no `import tfx` statement or similar in the spotify-tensorflow as far as I can see. There are usage of tensorflow-transform and tensorflow-data-validation but not tfx per se.

**Comment by andrewsmartin** [comment]
Ah, I see. Yeah, I guess we just depended on tfx so it could pull in the relevant component libs (TFT, TFDV etc) but we don't use anything else from there. Maybe we can just go back to depending on the individual libs. As a bonus, those are already available for 0.14 so it would actually unblock us upgrading tensorflow.

@brianmartin any thoughts?

**Comment by rculbertson** [comment]
Sounds like we're unnecessarily restricting what users can do? My vote is to depend on the individual libs.
