### ISSUE TITLE
Remove or Reevaluate the use of TF Flags

### ISSUE THREAD

**Issue by richwhitjr** [spotify/spotify-tensorflow#42]
Currently the library registers TF Flags in a few places.  This leads to few major problems.

1. Flag parser fails on unknown flags which can happen when using another library like jupyter.
2. Initialization order matters.  If new flags are needed they need to be declared prior to import sptf.
3. Also some issues with discoverability of the flags present.
4. __init__ usage currently registers the flags even if they aren't necessary.

**Comment by ravwojdyla** [comment]
For now the plan is to stick with tf.flags, there was bug in sptf introduced in #33 and fixed in #44 (which should fix some of the your 2nd problem). That said let's keep this issue open, if anyone wants to give this a shot and submit a PR.

**Comment by ravwojdyla** [comment]
Closed #74
