### ISSUE TITLE
Reevaluate if we need/want the Trainer class

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/spotify-tensorflow#49]
Trainer API is somewhat a blackbox, might be too high level, most of TF code standardizes on Estimator API, maybe it's fine to stay at Estimator API.

Any opinions @richwhitjr @yonromai ?

**Comment by yonromai** [comment]
I in favor of getting rid of it: abstractions have a cost and I don't think this one is bringing much value

**Comment by ravwojdyla** [comment]
@yonromai agree - let's remove it.
