### ISSUE TITLE
/ Inconsistency in job_dir

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/spotify-tensorflow#55]
https://github.com/spotify/spotify-tensorflow/blob/master/spotify_tensorflow/luigi/tensorflow_task.py#L89-L90

GCSFlagTarget requires the path to end with `/` while we also say:

https://github.com/spotify/spotify-tensorflow/blob/master/spotify_tensorflow/luigi/tensorflow_task.py#L65-L66

**Comment by brianmartin** [comment]
Here are permalinks for the above (master line numbers have drifted):
- https://github.com/spotify/spotify-tensorflow/blob/92c734bc113640557c0d655df192356176ad4b99/spotify_tensorflow/luigi/tensorflow_task.py#L89-L90
- https://github.com/spotify/spotify-tensorflow/blob/92c734bc113640557c0d655df192356176ad4b99/spotify_tensorflow/luigi/tensorflow_task.py#L65-L66

**Comment by brianmartin** [comment]
@andrewsmartin I believe this is resolved with #55. Would you mind closing?
