### ISSUE TITLE
Remove ExternalDailySnapshot after depending on luigi>=2.8.2

### ISSUE THREAD

**Issue by brianmartin** [spotify/spotify-tensorflow#95]

**Comment by brianmartin** [comment]
See https://github.com/spotify/luigi/pull/2591

**Comment by brianmartin** [comment]
It's been approved. Waiting on merge...

**Comment by brianmartin** [comment]
It's been merged https://github.com/spotify/luigi/commit/4b2b3d33e9aa26d542a71d52ebf1f1acd96dc681. Good to go with the next Luigi release (>2.8.0).

**Comment by andrewsmartin** [comment]
@brianmartin nice!

**Comment by brianmartin** [comment]
This is waiting on our common, internal image updating luigi. This should be in the next week or two.
