### ISSUE TITLE
Decide on "optional" dependencies location

### ISSUE THREAD

**Issue by brianmartin** [spotify/spotify-tensorflow#99]
Currently we have a `requirements.txt` and a `test-requirements.txt`. The `test-requirements.txt` includes more than strictly testing concerns: it also has "optional" dependencies. We should rejigger.

cc @andrewsmartin 

------

The `requirements.txt` has the most minimal packages necessary:
https://github.com/spotify/spotify-tensorflow/blob/d2f093d355a2caa67c1e1566b6b50f4fe4d478f9/requirements.txt#L1-L5

-------

The `test-requirements.txt` has testing utils such as `nose`, while also including "optional" dependencies like `tensorflow-transform`:

https://github.com/spotify/spotify-tensorflow/blob/d2f093d355a2caa67c1e1566b6b50f4fe4d478f9/test-requirements.txt#L3-L8

vs 

https://github.com/spotify/spotify-tensorflow/blob/d2f093d355a2caa67c1e1566b6b50f4fe4d478f9/test-requirements.txt#L12-L16

**Comment by andrewsmartin** [comment]
@brianmartin do you have any suggestions / best practices around this? I agree it feels a bit much to pull in TFT just for the `ExampleProtoCoder` needed in `tfread`, but I'm not sure what the best option is. `extra-requirements.txt`? That would still need an extra manual step for users if they want to use `tfread` right? Wondering if there's a bit too many separate concerns in this project...

**Comment by brianmartin** [comment]
We'll be using `extra_requires` to handle these separate sets of dependencies.

It's a good point on `tfr-read`, as-is that will fail to run after a `pip install spotify-tensorflow` in a fresh python environment. I'll open a separate issue for that concern.
